config/routes.rb
Crystal::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :teachers, controllers:{registrations: "teachers/registrations"}
  ActiveAdmin.routes(self)

  resources :teachers, :only=>[]  do 
    get :basicInfor, :on => :collection
    get :editInfor, :on => :collection
    get :editinfo_experience, :on => :collection
    get :editinfo_plan, :on => :collection
    get :editinfo_study, :on => :collection
    get :editinfo_basic, :on => :collection
    post :updateInfor, :on => :collection
    get :paper, :on => :collection
    post :upload, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_transfer, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :detail,:on => :collection
    get :gallery,:on=>:collection
    get :show_menu,:on=>:collection
    get :sign_today,:on=>:collection
  end

  devise_for :parents, controllers: { registrations: "parents/registrations", sessions: "parents/sessions" }
  ActiveAdmin.routes(self)

  devise_scope :parent do
    get '/parent_validate', to: 'parents/sessions#parent_validate'
  end

  resources :parents, :only => [] do 
    get :activity, :on => :collection
    get :profile, :on => :collection
    get :modify_info, :on => :collection
    put :modify_info_changed, :on => :collection
    get :modify_password, :on => :collection
    put :modify_password_changed, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_refund, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :show_menu,:on=>:collection
  end

  resources :courses do
    get :select_second, :on=>:collection
    get :select_third, :on=>:collection
  end

  resources :addresses
  
  resources :comments, :only => [:index, :new, :create]
  
  resources :orders, :only => [:new, :create] do
    get :parent, :on => :collection
    get :teacher, :on => :collection
    get :parent_pay, :on => :collection
    get :teacher_pay, :on => :collection
  end

  resources :trades, :only => [:show] do
    post :alipay_notify, :on => :collection
  end

  resources :messages, :only => [:show]

  resources :notices, :only => [:index, :show] do
    get :list, :on=>:collection
    get :download, :on => :collection
  end

  resources :information, :only=>[:index, :show, :new, :create] do
    get :download, :on => :collection
  end

  resources :institutions, :only=>[:index]

  match '/activities/bonus' => 'activities#bonus'
  match '/activities/beauty' => 'activities#beauty'
  match '/activities/beauty2' => 'activities#beauty2'
  #post '/activities/vote_create2' => 'activities#vote_create2'
  #post '/activities/vote_code_validate' => 'activities#vote_code_validate'

  match '/filters/index' => 'filters#index'
  match '/filters/search' => 'filters#search'
  match '/subject/:number' => 'filters#subject'
  match '/filters/select/:school/:grade/:course/:sex/:period/:time',:controller => 'filters',:action => 'select'
  match '/login' => 'home#login'
  match '/sign_up' => 'home#sign_up'
  match '/flow' => 'home#flow'
  match '/tflow' => 'home#tflow'

  root :to => 'home#index'
end

app/controllers/home_controller.rb
# encoding: UTF-8

class HomeController < ApplicationController
  layout "application_blank", :only => [:sign_up, :login]
  has_mobile_fu
  has_mobile_fu_for :login, :index

  def index
    ##个人信息只显示未读的, 其他信息已读和未读都显示
    #@messages = []
    #@group_messages = []
    #@public_messages = Message.where("category = #{Setting.messages.category_public} and status in (#{Setting.messages.status_unread}, #{Setting.messages.status_read})")
    #if parent_signed_in?
    #  @messages = Message.where("parent_id = #{current_parent.id} and category = #{Setting.messages.category_parent} and status = #{Setting.messages.status_unread}").order("id desc")
    #  @group_messages = Message.where("category = #{Setting.messages.category_parent_public} and status in (#{Setting.messages.status_unread}, #{Setting.messages.status_read})")
    #elsif teacher_signed_in?
    #  @messages = Message.where("teacher_id = #{current_teacher.id} and category = #{Setting.messages.category_teacher} and status = #{Setting.messages.status_unread}").order("id desc")
    #  @group_messages = Message.where("category = #{Setting.messages.category_teacher_public} and status in (#{Setting.messages.status_unread}, #{Setting.messages.status_read})")
    #end

    #@notices = Notice.limit(6).order("created_at desc")

    #if parent_signed_in?
    #  @num_dzf = 0
    #  @num_dsk = 0
    #  @orders = current_parent.orders
    #  @orders.each do |o|
    #    if o.status == Setting.orders.status_trade_created
    #      @num_dzf = @num_dzf + 1 
    #    elsif o.status == Setting.orders.status_teacher_paied
    #      @num_dsk = @num_dsk + 1 
    #    end
    #  end
    #elsif teacher_signed_in?
    #  @num_dqr = 0
    #  @num_dsk = 0
    #  @orders = current_teacher.orders
    #  @orders.each do |o|
    #    if o.status == Setting.orders.status_parent_paied
    #      @num_dqr = @num_dqr + 1 
    #    elsif o.status == Setting.orders.status_teacher_paied
    #      @num_dsk = @num_dsk + 1 
    #    end
    #  end
    #end

    @new_teachers = Teacher.where(:status => Setting.teachers.status_pass_sql).order("updated_at desc").limit(10)
    @normal_teachers = Teacher.where(:status => Setting.teachers.status_pass_sql).order("score desc").limit(100)
    @count = 0
    @courses = Course.where(:category_id => Category.where("second = '计算机'").select("id")).limit(100).group("teacher_id").order("created_at desc")
    @profess_teachers = @courses.map {|course| course.teacher if course.teacher}
    @profess_teachers.uniq!{|t| t.id}
    @profess_teachers.sort!{|a,b| b.score<=>a.score}
    @profess_teachers.reject!{|t| t.status != Setting.teachers.status_pass_sql}
    @profess_teachers = @profess_teachers[0..4]
  end
  
  def login
    @parent= Parent.new
    @teacher = Teacher.new
  end

  def sign_up
  end

  def flow
  end

  def tflow
  end

end

app/views/home/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <!-- Wrapper for slides -->

  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="bcimg1"></div>
    </div>
    <div class="item">
       <div class="bcimg2"></div>
    </div>
    <div class="item">
       <div class="bcimg3"></div>
    </div>
  </div>

</div>

app/views/home/_carousel.mobile.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("01.jpg", :width=>"100%", :alt => "最美家教") %>
    </div>
    <div class="item">
      <%= image_tag("02.jpg", :width=>"100%", :alt => "预约试讲") %>
    </div>
    <div class="item">
      <%= image_tag("03.jpg", :width=>"100%", :alt => "身份认证") %>
    </div>
  </div>

</div>

app/views/home/_message.html.haml
%div{:role=>"tabpanel"}
  %ul.nav.nav-tabs{:role=>"tablist"}
    %li.active{:role=>"presentation"}
      %a{:href=>"#message", "aria-controls"=>"message", :role=>"tab", "data-toggle"=>"tab"} 通知
    %li{:role=>"presentation"}
      %a{:href=>"#notice", "aria-controls"=>"notice", :role=>"tab", "data-toggle"=>"tab"} 新闻

  .tab-content
    %div.tab-pane.active#message{:role=>"tabpanel"}
      .notice-messages
        %ul
          - if parent_signed_in?
            - @public_messages.each do |message|
              %li.public-message= link_to "[公告] #{message.title}", msg_parents_path(:message=>message.id), :target=>"_blank"
              %li.pull-right
                =message.updated_at.strftime("%m-%d")
            - @group_messages.each do |message|
              %li.public-message= link_to "[公告] #{message.title}", msg_parents_path(:message=>message.id), :target=>"_blank"
              %li.pull-right
                =message.updated_at.strftime("%m-%d")
            - @messages.each do |message|
              %li.message= link_to "[我的] #{message.title}", msg_parents_path(:message=>message.id), :target=>"_blank"
              %li.pull-right
                =message.updated_at.strftime("%m-%d")
          - elsif teacher_signed_in?
            - @public_messages.each do |message|
              %li.public-message= link_to "[公告] #{message.title}", msg_teachers_path(:message=>message.id), :target=>"_blank"
              %li.pull-right
                =message.updated_at.strftime("%m-%d")
            - @group_messages.each do |message|
              %li.public-message= link_to "[公告] #{message.title}", msg_teachers_path(:message=>message.id), :target=>"_blank"
              %li.pull-right
                =message.updated_at.strftime("%m-%d")
            - @messages.each do |message|
              %li.message.pull-left= link_to "[我的] #{message.title}", msg_teachers_path(:message=>message.id), :target=>"_blank"
              %li.pull-right
                =message.updated_at.strftime("%m-%d")
          - else
            - @public_messages.each do |message|
              %li.public-message= link_to "[公告] #{message.title}", message, :target=>"_blank"
              %li.pull-right
                =message.updated_at.strftime("%m-%d")

    %div.tab-pane#notice{:role=>"tabpanel"}
      .notice-messages
        %ul
          - @notices.each do |notice|
            %li.public-message= link_to "[新闻] #{notice.title}", notice, :target=>"_blank"

app/views/home/_parents_new.html.haml
= form_for @parent, :url=>parent_session_path, :html=>{:class=>"form-horizontal"} do |f|
  /= devise_error_messages!
  .inputs
    .input-group
      .input-group-addon{:class => "left_bc"}
        %span{:class=>"glyphicon glyphicon-phone"}
      = f.text_field :phone, autofocus: true, :class=>"login-controls txt_left", :placeholder => "请输入手机号"
  .inputs
    .input-group
      .input-group-addon{:class => "left_bc"}
        %span{:class=>"glyphicon glyphicon-lock"}
      = f.password_field :password, autocomplete: "off", :class=>"login-controls txt-left", :placeholder => "请输入密码"


  .input_div
    = f.submit "登录", :class=>"btn btn-lg btn-block btn_back"

app/views/home/_parents_new.mobile.haml
= form_for @parent, :url=>parent_session_path, :html=>{:class=>"form-inline"} do |f|
  /= devise_error_messages!
  .col-xs-12
    .form-group
      = f.text_field :phone, autofocus: true, :class=>"form-control bd-radius", :placeholder => "请输入手机号"

  .col-xs-12
    .form-group
      = f.password_field :password, autocomplete: "off", :class=>"form-control bd-radius", :placeholder => "请输入密码"
  .col-xs-12
    .form-group
      = f.submit "登录", :class=>"btn  btn-block btn-warning"

app/views/home/_teachers_new.html.haml
= form_for @teacher, :url=>teacher_session_path, :html=>{:class=>"form-horizontal"} do |f|
  /= devise_error_messages!
  .inputs
    .input-group
      .input-group-addon{:class => "left_bc"}
        %span{:class=>"glyphicon glyphicon-phone"}
      = f.text_field :phone, autofocus: true, :class=>"login-controls txt_left", :placeholder => "请输入手机号"
  .inputs
    .input-group
      .input-group-addon{:class => "left_bc"}
        %span{:class=>"glyphicon glyphicon-lock"}
      = f.password_field :password, autocomplete: "off", :class=>"login-controls txt-left", :placeholder => "请输入密码"

  .input_div
    = f.submit "登录", :class=>"btn btn-lg btn-block btn_back"

app/views/home/_teachers_new.mobile.haml
= form_for @teacher, :url=>teacher_session_path, :html=>{:class=>"form-inline"} do |f|
  /= devise_error_messages!
  .col-xs-12
    .form-group
      = f.text_field :phone, autofocus: true, :class=>"form-control bd-radius", :placeholder => "请输入手机号"

  .col-xs-12
    .form-group
      = f.password_field :password, autocomplete: "off", :class=>"form-control bd-radius", :placeholder => "请输入密码"
  .col-xs-12
    .form-group
      = f.submit "登录", :class=>"btn  btn-block btn-warning"

app/views/home/flow.html.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top"
= render "layouts/nav_menu"
.apw_ctn
  .apw_ctt
    = link_to "家长注册", new_parent_registration_path, :class => "btn btn-primary btn-lg register_btn"

  -#
    %ul.apw_ul
      %li
        .apw_img.no1_img
        .apw_int 
          %p.apw_title 搜课程
          %p 根据年级、科目等分类在家教呢平台搜索您需要的课程
      %li
        .apw_img.no2_img
        .apw_int 
          %p.apw_title 确定试讲时间
          %p 选定自己需要的课程后，填写试讲地点并确定试讲时间
      %li
        .apw_img.no3_img
        .apw_int 
          %p.apw_title  支付试讲费用
          %p 您需要支付首次试讲的试讲费用，如果您对试讲不满意，该费用将退回您的账户
      %li
        .apw_img.no4_img
        .apw_int 
          %p.apw_title 等待老师接单
          %p 老师接单后，将发送给你试讲满意验证码，如果您对试讲不满意，请不要将反馈码告知家教，试讲费用将退回您的账户
      %li
        .apw_img.no5_img
        .apw_int 
          %p.apw_title 完成
          %p 完成实地试讲，并对课程进行评价

app/views/home/index.mobile.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top" 

.row.filter-top.form-group
  = render "carousel" 
  
.row.bd-bottom.border-shadow 
  .col-xs-12.user-details 
    .user-info-block 
      %Ul.row.navigation 
        %li.col-xs-2
          = link_to "全部", "/filters/index",  :class => "decoration-none col-xs-12"
        %li.col-xs-2.active
          %a{ :'data-toggle' => "tab", :href => "#primary", :class => "decoration-none col-xs-12"}
            小学
        %li.col-xs-2
          %a{ :'data-toggle' => "tab", :href => "#junior", :class => "decoration-none col-xs-12"}
            初中
        %li.col-xs-2
          %a{ :'data-toggle' => "tab", :href => "#high", :class => "decoration-none col-xs-12"}
            高中
        -#
          %li.col-xs-2
            %a{ :'data-toggle' => "tab", :href => "#art", :class => "decoration-none col-xs-12"}
              艺术
        %li.col-xs-4
          %a{ :'data-toggle' => "tab", :href => "#compute", :class => "decoration-none col-xs-12"}
            计算机
      .user-body
        .tab-content
          .tab-pane.active#primary
            .row
              .col-xs-12
                %ul{:class => "list-inline margin-zero"}
                  %li
                    = link_to "数学","/subject/1/", :class => "decoration-none"
                  %li
                    = link_to "语文","/subject/2/", :class => "decoration-none"
                  %li
                    = link_to "英语","/subject/3/", :class => "decoration-none"
                  %li
                    = link_to "作文","/subject/4/", :class => "decoration-none"
          .tab-pane#junior
            .row
              .col-xs-12
                %ul{:class => "list-inline margin-zero"}
                  %li
                    = link_to "数学","/subject/11/", :class => "decoration-none"
                  %li
                    = link_to "语文","/subject/12/", :class => "decoration-none"
                  %li
                    = link_to "物理","/subject/15/", :class => "decoration-none"
                  %li
                    = link_to "化学","/subject/16/", :class => "decoration-none"
                  %li
                    = link_to "英语","/subject/13/", :class => "decoration-none"
                  %li
                    = link_to "历史","/subject/18/", :class => "decoration-none"
                  %li
                    = link_to "政治","/subject/17/", :class => "decoration-none"
                  %li
                    = link_to "生物","/subject/14/", :class => "decoration-none"
          .tab-pane#high
            .row
              .col-xs-12
                %ul{:class => "list-inline margin-zero"}
                  %li
                    = link_to "数学","/subject/21/", :class => "decoration-none"
                  %li
                    = link_to "语文","/subject/22/", :class => "decoration-non"
                  %li
                    = link_to "物理","/subject/25/", :class => "decoration-none"
                  %li
                    = link_to "化学","/subject/26/", :class => "decoration-none"
                  %li
                    = link_to "英语","/subject/23/", :class => "decoration-none"
                  %li
                    = link_to "历史","/subject/28/", :class => "decoration-none"
                  %li
                    = link_to "政治","/subject/27/", :class => "decoration-none"
                  %li
                    = link_to "生物","/subject/24/", :class => "decoration-none"
          -#
            .tab-pane#art
            .row
              .col-xs-12
                %ul{:class => "list-inline margin-zero"}
                  %li
                    = link_to "音乐", nil, :class => "decoration-none"
                  %li
                    = link_to "舞蹈", nil, :class => "decoration-none"
                  %li
                    = link_to "美术", nil, :class => "decoration-none"
                  %li
                    = link_to "体育", nil, :class => "decoration-none"
          .tab-pane#compute
            .row
              .col-xs-12
                %ul{:class => "list-inline margin-zero"} 
                  %li
                    = link_to "Java","/subject/51/", :class => "decoration-none"
                  %li
                    = link_to "网页制作","/subject/56/", :class => "decoration-none"
                  %li
                    = link_to "办公软件","/subject/58/", :class => "decoration-none"
.row.bd-bottom
  .col-xs-12.margin-zero
    .row
      .col-xs-12
        %P
          %h5
            小初高教育 
  %ul.col-xs-12.padding-none.margin-zero
    - @normal_teachers.each_with_index do |f,i|
      - next if f.courses[0] and f.courses[0].category and f.courses[0].category.second == "计算机"
      - @count += 1
      - break if @count == 11
      %li.col-xs-6.topt
        %a{:href => detail_teachers_path(:id => f.number)}
          .col-xs-12
            %P.text-center
              = image_tag(f.image_url(:normal),:class=>"img-circle", :width => "80px", :height => "80px", :alt=>"老师")
            %P
              %h4.text-center.text-muted
                = f.name
            .col-xs-12.form-group.detail-comment-tips
              %ul.ful
                %li.stuff &nbsp;
                %li.stuff &nbsp;
                %li.stuff &nbsp;
                %li.stuff &nbsp;
                %li.stuff &nbsp;
            %p.text-muted
              - if f.courses[0] and f.courses[0].category
                = f.courses[0].category.second+f.courses[0].category.subject
              &nbsp;
              &nbsp;
              %small.font-orange
                = f.teaching_age.to_s() + "年教龄"
            %P
              %h4.text-left.text-muted
                - if f.identity == 1 and f.student_identity
                  = f.student_identity.major
                -else
                  = "东北电力大学"
    -#              
        - if f.period == 0
          = image_tag("jb3.png")
        - elsif f.period == 1
          = image_tag("jb1.png")
        - if f.identity == 1 and f.student_identity
          = "\-"
          %span= f.student_identity.school
.row.bd-bottom
  .col-xs-12.margin-zero
    .row
      .col-xs-12
        %P
          %h5
            专业教育
  %ul.col-xs-12.padding-none.margin-zero
    - @profess_teachers.each_with_index do |f,i|
      %li.col-xs-12.newt
        %a{:href => detail_teachers_path(:id => f.number)}
          .col-xs-4
            %P
              = image_tag(f.image_url(:normal),:class=>"img-circle", :width => "80px", :height => "80px", :alt=>"老师")
          .col-xs-8
            %P
              %h4.text-muted
                = f.name
                &nbsp;
                &nbsp;
                %small.font-orange
                  = f.teaching_age.to_s() + "年教龄"
            %P.text-muted
              - if f.identity == 1 and f.student_identity
                = f.student_identity.major
              -else
                = "东北电力大学"
            %p.text-muted
              - if f.courses[0] and f.courses[0].category
                = f.courses[0].category.subject

-#
  .row.bd-bottom
  .col-xs-12.margin-zero
    .row
      .col-xs-3
        %P
          %h5
            最新入驻
  %ul.col-xs-12.padding-none.margin-zero
    - @new_teachers.each_with_index do |f,i|
      %li.col-xs-12.newt
        %a{:href => detail_teachers_path(:id => f.number)}
          .col-xs-4
            %P
              = image_tag(f.image_url(:normal),:class=>"img-circle", :width => "80px", :height => "80px", :alt=>"老师")
          .col-xs-8
            %P
              %h4.text-muted
                = f.name
                &nbsp;
                &nbsp;
                %small.font-orange
                  = f.teaching_age.to_s() + "年教龄"
            %P.text-muted
              - if f.identity == 1 and f.student_identity
                = f.student_identity.major
              -else
                = "东北电力大学"
            %p.text-muted
              = f.courses[0,3].map{|course| course.category.second[0]+course.category.third[0]+course.category.subject}.join(",").html_safe

app/views/home/login.html.haml
- provide(:title, t('.title'))

.login_container.autowidth
  .login_main
    .left
      =image_tag('denglu1.jpg', :class=>"bgimg")
    .right
      %ul.nav_back.nav.nav-tabs.login-nav-tabs{:role=>"tablist"}
        %li.nav_no.active.nav_text= link_to "家长登录", "#parent_sign_in", :role=>"tab", "data-toggle"=>"tab"
        %li.nav_no.nav_text= link_to "家教登录", "#teacher_sign_in", :role=>"tab", "data-toggle"=>"tab"
                                                                                
      .login-panel
        .tab-content
          .tab-pane.fade.in.active#parent_sign_in
            = render "parents_new"                                                                          
          .tab-pane.fade#teacher_sign_in                                                                    
            = render "teachers_new"                  
      .input_div
        .row
          .col-md-4
            = link_to "家长注册", new_parent_registration_path, :class=>"login_reg"
          .col-md-4.col-md-offset-4.reg_align
            = link_to "家教注册", new_teacher_registration_path, :class=>"login_reg"

app/views/home/login.mobile.haml
- provide(:title, t('.title'))
.row
  .col-xs-12
    .row
      .col-xs-12
        .login-panel{:role => "tabpanel"}
          %ul.nav.nav-tabs.nav_back.login-nav-tabs{:role=>"tablist"}
            %li.active.nav_no.nav_text.bd-right{:role => "presentation"}= link_to "家长登录", "#parent_sign_in", :'aria-controls' => "parent_sign_in", :role => "tab", "data-toggle" => "tab"
            %li.nav_no.nav_text{:role => "presentation"}= link_to "家教登录", "#teacher_sign_in", :'aria-controls' => "teacher_sign_in", :role=>"tab", "data-toggle"=>"tab"
          .row
            .col-xs-12
              .tab-content
                .tab-pane.active#parent_sign_in{:role => "tabpanel"}
                  = render "parents_new"
                .tab-pane#teacher_sign_in{:role => "tabpanel"}
                  = render "teachers_new"

        %br
        .login-panel{:role => "tabpanel"}
          .sign-up-text 如果您还没有帐号，请先注册
          .row
            .col-xs-12
              .col-xs-6
                %p
                  %h3.text-center
                    = link_to "家长注册", new_parent_registration_path, :class=>"btn btn-default btn-block"
              .col-xs-6
                %p
                  %h3.text-center
                    = link_to "家教注册", new_teacher_registration_path, :class=>"btn btn-default btn-block"

app/views/home/sign_up.html.haml
- provide(:title, t('.title'))

.reg_cnt
  .preg_img
    = image_tag('pword.png',:class=>"pword")
    = link_to "家长注册",new_parent_registration_path, :class=>"btn btn-lg btn-success preg_btn" 
  .split_line
  .treg_img
    = image_tag('tword.png',:class=>"tword")
    = link_to "家教注册",new_teacher_registration_path, :class=>"btn btn-lg btn-success reg_btn"

app/views/home/tflow.html.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top"
= render "layouts/nav_menu"

.apw_ctn
  .teacher_ctt
    = link_to "家教注册", new_teacher_registration_path, :class => "btn btn-primary btn-lg  register_t_btn"