config/routes.rb
Crystal::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :teachers, controllers:{registrations: "teachers/registrations"}
  ActiveAdmin.routes(self)

  resources :teachers, :only=>[]  do 
    get :basicInfor, :on => :collection
    get :editInfor, :on => :collection
    get :editinfo_experience, :on => :collection
    get :editinfo_plan, :on => :collection
    get :editinfo_study, :on => :collection
    get :editinfo_basic, :on => :collection
    post :updateInfor, :on => :collection
    get :paper, :on => :collection
    post :upload, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_transfer, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :detail,:on => :collection
    get :gallery,:on=>:collection
    get :show_menu,:on=>:collection
    get :sign_today,:on=>:collection
  end

  devise_for :parents, controllers: { registrations: "parents/registrations", sessions: "parents/sessions" }
  ActiveAdmin.routes(self)

  devise_scope :parent do
    get '/parent_validate', to: 'parents/sessions#parent_validate'
  end

  resources :parents, :only => [] do 
    get :activity, :on => :collection
    get :profile, :on => :collection
    get :modify_info, :on => :collection
    put :modify_info_changed, :on => :collection
    get :modify_password, :on => :collection
    put :modify_password_changed, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_refund, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :show_menu,:on=>:collection
  end

  resources :courses do
    get :select_second, :on=>:collection
    get :select_third, :on=>:collection
  end

  resources :addresses
  
  resources :comments, :only => [:index, :new, :create]
  
  resources :orders, :only => [:new, :create] do
    get :parent, :on => :collection
    get :teacher, :on => :collection
    get :parent_pay, :on => :collection
    get :teacher_pay, :on => :collection
  end

  resources :trades, :only => [:show] do
    post :alipay_notify, :on => :collection
  end

  resources :messages, :only => [:show]

  resources :notices, :only => [:index, :show] do
    get :list, :on=>:collection
    get :download, :on => :collection
  end

  resources :information, :only=>[:index, :show, :new, :create] do
    get :download, :on => :collection
  end

  resources :institutions, :only=>[:index]

  match '/activities/bonus' => 'activities#bonus'
  match '/activities/beauty' => 'activities#beauty'
  match '/activities/beauty2' => 'activities#beauty2'
  #post '/activities/vote_create2' => 'activities#vote_create2'
  #post '/activities/vote_code_validate' => 'activities#vote_code_validate'

  match '/filters/index' => 'filters#index'
  match '/filters/search' => 'filters#search'
  match '/subject/:number' => 'filters#subject'
  match '/filters/select/:school/:grade/:course/:sex/:period/:time',:controller => 'filters',:action => 'select'
  match '/login' => 'home#login'
  match '/sign_up' => 'home#sign_up'
  match '/flow' => 'home#flow'
  match '/tflow' => 'home#tflow'

  root :to => 'home#index'
end

app/controllers/teachers/registrations_controller.rb
class Teachers::RegistrationsController < Devise::RegistrationsController
  layout "application_blank", :except=>["edit", "update"]
  has_mobile_fu
  has_mobile_fu_for :new,:edit

  def create
    super
  end

  def after_sign_up_path_for(resource)
    '/teachers/basicInfor'
  end
end

app/controllers/teachers_controller.rb
# encoding: UTF-8

require 'rmagick'
require 'chunky_png/rmagick'

class TeachersController < ApplicationController
  layout "application_blank", :only => [:sign_up, :login]
  before_filter :authenticate_teacher!, :except => [:detail]
  load_and_authorize_resource :except => [:detail]
  has_mobile_fu
  has_mobile_fu_for :detail,:editinfo_basic,:show_menu,:editinfo_plan,:gallery,:messages,:order_all,:order_unpay,:order_reserving,:order_transfer,:basicInfor,:editinfo_study,:editinfo_experience

  def basicInfor
    @orders = current_teacher.orders.find(:all,:conditions => {:status => Setting.orders.status_parent_paied},:order => "created_at desc")

    basicInfo_judge
    study_judge
    experience_judge
    plan_judge
  end

  def editinfo_experience
    editInfor
  end

  def editinfo_plan
    editInfor
  end

  def editinfo_study
    editInfor
  end

  def editinfo_basic
    editInfor
  end

  def editInfor
    if current_teacher.scores.length == 0
      current_teacher.scores.build
    end
    if current_teacher.honors.length == 0
      current_teacher.honors.build
    end
    if current_teacher.pictures.length == 0
      current_teacher.pictures.build
    end
    if current_teacher.careers.length == 0
      current_teacher.careers.build
    end

    @appointments_pos =[]
    current_teacher.appointments.each do |appointment|
      @appointments_pos << appointment.weekday
    end 
  end


  def updateInfor
    current_teacher.status = Setting.teachers.status_edit_sql

    if params[:info]
      current_teacher.status = Setting.teachers.status_edit_sql
    end

    if params[:remove_honors_image]
      params[:remove_honors_image].each do |r|
        current_teacher.pictures[r.to_i].remove_honors_image!
      end
        Picture.delete_all(:honors_image=>nil)
    end

    identity=current_teacher.identity
    if identity==Setting.teachers.identity_student
      if current_teacher.student_identity
        current_teacher.student_identity.update_attributes(params[:student_identity])
      else
        current_teacher.create_student_identity(params[:student_identity]) 
      end
    elsif identity==Setting.teachers.identity_teacher
      if current_teacher.teacher_identity
        current_teacher.teacher_identity.update_attributes(params[:teacher_identity])
      else
        current_teacher.create_teacher_identity(params[:teacher_identity]) 
      end
    end

    #TODO: 没有选择预约时间时给出错误提示, 需要通过validate来实现
    #TODO: 当update_attributes失败时，会保存一些没有关联的appointment到数据库
    @appointments_pos = params[:appointments_pos]
    if @appointments_pos
      Appointment.delete_all(:teacher_id=>current_teacher.id)
      @appointments_pos = @appointments_pos.map {|p| p.to_i}
      @appointments_pos.each do |pos|
        @appointment = Appointment.new(:weekday=>pos)
        #@appointment.time = pos / 7 + 1
        #@appointment.weekday = pos % 7 + 1
        @appointment.teacher = current_teacher
        @appointment.save
      end
    end

    if current_teacher.update_attributes(params[:teacher])
      flash.now[:success] = t('teachers.editInfor.success')
      redirect_to basicInfor_teachers_url
    else
      flash.now[:error] = t('teachers.editInfor.error')
      @appointments_pos = []
      render action: "editinfo_basic"
    end
  end

  def paper
  end

  def upload
    item_img=params[:item_img]
    if item_img==Setting.teachers.item_img_basic.to_s
      current_teacher.status = Setting.teachers.status_edit_sql
    end
    if params[:galleries]
      @gallery=Gallery.new(params[:galleries])
      @gallery.teacher=current_teacher
      @gallery.save
    end
    if current_teacher.update_attributes(params[:teacher])
      flash.now[:success] = t('teachers.upload.success')
    else
      flash.now[:error] = t('teachers.upload.error')
    end
    if item_img==Setting.teachers.item_img_paper.to_s
      redirect_to paper_teachers_url
    elsif item_img==Setting.teachers.item_img_basic.to_s
      redirect_to editInfor_teachers_url
    elsif item_img==Setting.teachers.item_img_gallery.to_s
      redirect_to gallery_teachers_url
    end
    if params[:remove_galleries_image]
      params[:remove_galleries_image].each do |r|
        current_teacher.galleries[r.to_i].remove_photo!
      end
      Gallery.delete_all(:photo=>nil)
    end

  end

  def order_all
    @orders = current_teacher.orders.find(:all,:order => "created_at desc")
    @orders = @orders.select {|o| [Setting.orders.status_parent_paied, Setting.orders.status_teacher_paied, Setting.orders.status_trade_success, Setting.orders.status_trade_failed].include?(o.status)}
  end

  def order_unpay
    @orders = current_teacher.orders.find(:all,:conditions => {:status => Setting.orders.status_parent_paied},:order => "created_at desc")
  end

  def order_reserving
    @orders = current_teacher.orders.find(:all,:conditions => {:status => Setting.orders.status_teacher_paied},:order => "created_at desc")
  end

  def order_transfer
    @orders = current_teacher.orders.find(:all,:conditions => {:status => Setting.orders.status_trade_success},:order => "created_at desc")
  end

  def messages
    @messages = Message.where("teacher_id = #{current_teacher.id} and category = #{Setting.messages.category_teacher} and status in (#{Setting.messages.status_unread}, #{Setting.messages.status_read})")
    @group_messages = Message.where("category = #{Setting.messages.category_teacher_public} and status in (#{Setting.messages.status_unread}, #{Setting.messages.status_read})")
    @public_messages = Message.where("category = #{Setting.messages.category_public} and status in (#{Setting.messages.status_unread}, #{Setting.messages.status_read})")
  end
  
  def msg
    @message = Message.find(params[:message])
    @message.update_attribute :status, Setting.messages.status_read
  end

  def detail
    @teacher = Teacher.find_by_number(params[:id])
    @course_json = @teacher.courses.to_json
    @careers = @teacher.careers.order("start_time DESC")
    @appointments = @teacher.appointments.map {|a| a.weekday}
    @active_dates = []
    (1..31).each do |step|
      if @appointments.include? (Time.now + step.days).wday
        @active_dates << (Time.now + step.days).strftime("%-d/%-m/%Y")
      end
    end
    gon.active_dates = @active_dates
    @parent = Parent.new

    @comments = @teacher.comments
    @good_num = 0;
    @medium_num = 0;
    @bad_num = 0;
    @comments.each do |comment|
      if comment.total == Setting.comments.total_good
        @good_num += 1
      elsif comment.total == Setting.comments.total_medium
        @medium_num += 1
      else
        @bad_num += 1
      end
    end
  end

  def gallery
    if current_teacher.galleries.length == 0
      current_teacher.galleries.build
    end
  end

  def sign_today
    current_date = Time.now.strftime("%Y%m%d")
    if current_teacher.signdate.last != current_date
      if current_teacher.signdate.last == (Time.now-1.day).strftime("%Y%m%d")
        current_teacher.signcount += 1
      else
        current_teacher.signcount = 1
      end
      current_teacher.signdate << current_date
      current_teacher.save
    end
    redirect_to basicInfor_teachers_url
  end
  
  private
  def basicInfo_judge
    if current_teacher.name.blank? || current_teacher.age.blank? || current_teacher.sex.blank? || current_teacher.hobby.blank? || current_teacher.introduction.blank? ||current_teacher.paper_img.blank? || current_teacher.image.blank? || current_teacher.teaching_age.blank?
      @basic_degree = 0  
    end
    
    identity=current_teacher.identity
    if identity==Setting.teachers.identity_student
      if current_teacher.student_identity.nil? || current_teacher.student_identity.school.blank? ||  current_teacher.student_identity.school.blank? || current_teacher.student_identity.school.blank? 
        @basic_degree = 0
      end
    elsif identity==Setting.teachers.identity_teacher
      if current_teacher.teacher_identity.nil? || current_teacher.teacher_identity.school.blank? ||  current_teacher.teacher_identity.grade.blank? || current_teacher.teacher_identity.subject.blank? 
        @basic_degree = 0
      end
    end
  end

  def study_judge
    if current_teacher.scores.blank? || current_teacher.pictures.blank? || current_teacher.honors.blank?
      @study_degree = 0
    end
  end

  def experience_judge
    if current_teacher.careers.blank?
      @experience_degree = 0
    end
  end

  def plan_judge
    if current_teacher.appointments.blank? 
      @plan_degree = 0
    end
  end

  def show_menu
  end

  def download
    @teacher = Teacher.find_by_number(params[:id])
    data = open(File.join(Rails.root, 'public', 'pictures', @Teacher.qrcode_uid))
    send_data data.read, :filename=>"#{@teacher.name}.png", :type => "application/force-download", :x_sendfile=>true
  end
end

app/helpers/teachers_helper.rb
# coding: utf-8
module TeachersHelper

  def get_teacher_status
    d = [
          [Setting.teachers.status_none, Setting.teachers.status_none_sql],
          [Setting.teachers.status_edit, Setting.teachers.status_edit_sql],
          [Setting.teachers.status_not_pass, Setting.teachers.status_notpass_sql],
          [Setting.teachers.status_pass, Setting.teachers.status_pass_sql]
        ]
  end

  def get_teacher_identity
    identity = [
          [Setting.teachers.identity_student_string,Setting.teachers.identity_student],
          [Setting.teachers.identity_teacher_string,Setting.teachers.identity_teacher]
        ]
  end
  
  def get_teacher_status_string(status)
    if status == Setting.teachers.status_none_sql
      Setting.teachers.status_none
    elsif status == Setting.teachers.status_edit_sql
      Setting.teachers.status_edit
    elsif status == Setting.teachers.status_notpass_sql
      Setting.teachers.status_not_pass
    elsif status == Setting.teachers.status_pass_sql
      Setting.teachers.status_pass
    end
  end
end

app/views/teachers/_editinfo_timage.html.haml
= form_for current_teacher,:url=>upload_teachers_path,:html => {:multipart => true,:method=>'post'} do |t|
  .col-md-6
    .panel.panel-default.basicpanel-height.b-radius
      .panel-heading.b-radius
        %strong个人头像
      .panel-body
        .row
          .col-md-6
            -if current_teacher.image.blank?
              =image_tag("user.png",:class=>"img-circle",:width=>"120px",:height=>"120px")
            -else
              = image_tag(current_teacher.image_url(:normal),:width=>"120px",:height=>"120px",:class=>"img-circle")
          .col-md-6.tp-left
            %P
              1.请使用近期照片   
            %p
              2.照片不大于3M 
            %p  
              = t.file_field :image
  
  .col-md-6
    .panel.panel-default.basicpanel-height.b-radius
      .panel-heading.b-radius
        %strong个人证件(*必填，否则无法发布课程)
      .panel-body.text-danger
        .row
          .col-md-6
            -if current_teacher.paper_img.blank?
              =image_tag("paper.jpg",:class=>"img-circle",:width=>"120",:height=>"120px")
            -else
              = image_tag(current_teacher.paper_img_url(:normal),:width=>"120px",:height=>"120px",:class=>"img-circle")
          .col-md-6.tp-left
            %p
              1.学生使用需学生证
            %p
              2.家教使用教师资格证
            %p
              3.认证通过才能发布课程
            %p
              = t.file_field :paper_img

app/views/teachers/detail.mobile.haml
- if @teacher.identity == 1 and @teacher.student_identity
  - provide(:title, "吉林-" + @teacher.name + "-" + @teacher.student_identity.school + "-" + @teacher.courses.map {|course| course.category.second[0]+course.category.third[0]+course.category.subject}.join(", "))
- else
  - provide(:title, "吉林-" + @teacher.name + "-" + @teacher.courses.map {|course| course.category.second[0]+course.category.third[0]+course.category.subject}.join(", "))
= render "layouts/subbar_top"

.row.form-group.filter-top
  .col-xs-12.back-white
    .row.header-padding
      .col-xs-3.m-top-10
        = image_tag(@teacher.image_url(:normal),:class => "img-circle", :width => "50px", :height => "50px")
      .col-xs-9
        %h4
          = @teacher.name 
          %small 
            - if @teacher.identity == Setting.teachers.identity_student
              - if @teacher.student_identity
                =t('teachers.detail.student')
            - else 
              - if @teacher.teacher_identity
                =t('teachers.detail.teacher')
        .row
          .col-xs-5
            = @teacher.teaching_age.to_s() + t('teachers.infor.teaching_age')
          .col-xs-7
            - if @teacher.identity == Setting.teachers.identity_student
              =t('teachers.infor.major')+@teacher.student_identity.major
            - else 
              =t('teachers.infor.subject')+@teacher.teacher_identity.subject
          
    .row.border-btm.border-shadow
      .tabbable-panel
        .tabbable-line
          %ul{:class => "nav nav-tabs", :role => "tablist" }
            %li.active.col-xs-4    
              %a{:href => "#idcard", :'data-toggle' => "tab"}
                = t('teachers.infor.idcard')
            %li.col-xs-4
              %a{:href => "#result", :'data-toggle' => "tab"}
                = t('teachers.infor.results')
            %li.col-xs-4
              %a{:href => "#experience", :'data-toggle' => "tab"}
                = t('teachers.infor.experience')
.row.form-group               
  .col-xs-12
    .tab-content
      .tab-pane.active#idcard
        .panel.bd-radius.border.panel-top
          .panel-heading.panel-heading-padding
            .row{:onclick => "togglecontent(this)"}
              .col-xs-10
                %h4
                  基本信息 
              .col-xs-2
                %h4
                  %i{:class => "glyphicon glyphicon-chevron-down"}
          .panel-body.padding-top-none.display-none
            .row
              .col-xs-6
                姓名:
                = @teacher.name
              .col-xs-6  
                年龄:
                = @teacher.age.to_s() +"岁"
              .col-xs-12
                现居地点:
                - if @teacher.address
                  = get_address_province_string(@teacher.address.province) + get_address_city_string(@teacher.address.city) + get_address_district_string(@teacher.address.district) + get_address_details_string(@teacher.address.details)
                - else
                  吉林省吉林市
              .col-xs-12    
                个人爱好:
                = @teacher.hobby

        .panel.bd-radius.border.panel-top
          .panel-heading.panel-heading-padding
            .row{:onclick => "togglecontent(this)"}
              .col-xs-10
                %h4
                  个人简介
              .col-xs-2
                %h4
                  %i{:class => "glyphicon glyphicon-chevron-down"}
          .panel-body.padding-top-none.display-none
            %p= format_string_newline(@teacher.introduction).html_safe
        .panel.bd-radius.border
          .panel-heading.panel-heading-padding
            .row{:onclick => "togglecontent(this)"}
              .col-xs-10
                %h4
                  我的评价
              .col-xs-2
                %h4
                  %i{:class => "glyphicon glyphicon-chevron-down"}
          .panel-body.padding-top-none.display-none
            .row
              .col-xs-12
                %ul.list-inline
                  %li= "好评 (#{@good_num})"
                  %li= "中评 (#{@medium_num})"
                  %li= "差评 (#{@bad_num})"
              .col-xs-12
                %ul.list-group
                  - @comments.each do |comment|
                    %Li.list-group-item.padding-none
                      .well.well-sm.border-shadow-none.border-none.back-white.bd-radius.margin-zero
                        .row
                          .col-xs-3.text-center
                            = image_tag("head.png", :class=>"img-circle", :width => "60px", :height => "60px", :alt=>"小学老师")
                          .col-xs-9.section-box
                            .row
                              .col-xs-4
                                %p
                                  = comment.parent.name
                            -#
                              .col-xs-12
                                = comment.content
                            %hr
                            .row.rating-desc
                              .col-xs-12
                                - if comment.total == Setting.comments.total_good
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star
                                - elsif comment.total == Setting.comments.total_medium
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star-empty
                                  %span.glyphicon.glyphicon-star-empty
                                - else
                                  %span.glyphicon.glyphicon-star
                                  %span.glyphicon.glyphicon-star-empty
                                  %span.glyphicon.glyphicon-star-empty
                                  %span.glyphicon.glyphicon-star-empty
                                  %span.glyphicon.glyphicon-star-empty

        .panel.bd-radius.border.panel-top
          .col-xs-12.padding-none
            %ul.list-group.bd-radius.modal-height
              - @teacher.courses.each_with_index do |course,n|
                %li.list-group-item.bd-radius
                  .row
                    .col-xs-9
                      = course.name
                    .col-xs-3.font-orange
                      = "￥" + course.price
          .col-xs-12.back-white.border
            .row
              .col-xs-12
                %p
                  %h4
                    上课时间
            .row
              .col-xs-12
                #appointment-time
      .tab-pane#result
        .col-xs-12.padding-none
          %ul.list-group.bd-radius
            %li.list-group-item.bd-radius
              .row
                .col-xs-9
                  我的成绩单
            - @teacher.scores.each_with_index do |s,i|
              %li.list-group-item.bd-radius
                .row
                  .col-xs-4
                    .text-center
                      = i+1
                  .col-xs-4
                    .text-center
                      = s.title
                  .col-xs-4
                    .text-center
                      = s.content
        .col-xs-12.padding-none
          %ul.list-group.bd-radius
            %li.list-group-item.bd-radius
              .row
                .col-xs-9
                  我的荣誉单
            - @teacher.honors.each do |s|
              %li.list-group-item.bd-radius
                .row
                  .col-xs-4
                    = s.title
                  .col-xs-8
                    = s.content
      .tab-pane#experience
        .col-xs-12.padding-none
          %ul.list-group.bd-radius
            %li.list-group-item.bd-radius
              .row
                .col-xs-9
                  我的教学经历
            - @careers.each do |c|
              %li.list-group-item.padding-eight.bd-radius
                - if c.start_time and c.end_time
                  %p
                    %h4.font-orange
                      = c.start_time.strftime("%Y-%m")+' 到 '+c.end_time.strftime("%Y-%m") + ' 辅导 : '+c.subject 
                  %p  
                    = c.content
                  
%button.btn.btn-block.btn-warning{:"data-toggle"=>"modal",:"data-target"=>"#allcourses"}
  预约课程
  = render "date"

.modal.fade#allcourses
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{:"data-dismiss"=>"modal",:"aria-label"=>"Close"}
          %span{:"aria-hidden"=>"true"}
            &times;
        %h4.modal-title 课程列表
      = form_tag new_order_path, :method=>:get, :html=>{:class=>"form-horizontal"} do |f|
        .modal-body.modal-height 
          - @teacher.courses.each_with_index do |course,n|
            .row
              .col-xs-2
                -if n == 0
                  = radio_button("course","id", course.id, :checked => "checked")
                -else
                  = radio_button("course","id", course.id)
              .col-xs-6
                = course.name
              .col-xs-2.font-orange
                = "￥" + course.price
            %hr
        .modal-footer
          %button.btn.btn-default{:"data-dismiss"=>"modal"}
            取消订单
          = submit_tag "预约课程", :class=>"btn btn-warning "
.modal{:class=>"fade",:id=>"loginModal",:tabindex=>"-1",:role=>"dialog",:'aria-labelledby'=>"myModalLabel",:'aria-hidden'=>"true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button{:type=>"button",:class=>"close",:'data-dismiss'=>"modal"}
          %span{:'aria-hidden'=>"true",:class=>"glyphicon glyphicon-remove"}
          %span{:class=>"sr-only"}= "Close"
        %h5{:class=>"modal-title",:id=>"myModalLabel"}
          = "家长登录"
      .modal-body
        = form_for @parent, :url=>parent_session_path, :html=>{:class=>"form-horizontal"} do |f|
          /= devise_error_messages!
          .form-group
            .col-xs-12
              .error_message
          .form-group
            .col-xs-12
              = f.text_field :phone, autofocus: true, :class=>"form-control bd-radius", :placeholder => "请输入手机号"
          .form-group  
            .col-xs-12
              = f.password_field :password, autocomplete: "off", :class=>"form-control bd-radius", :placeholder => "请输入密码"
          .form-group  
            .col-xs-12
              %input{:type => "button",:value => "登录", :class=>"bd-radius btn btn-lg btn-block btn-warning",:onclick => "parent_validate()"}
          .form-group  
            .col-xs-12
              = link_to "家长注册", new_parent_registration_path, :class=>"bd-radius btn btn-lg btn-warning btn-block"

app/views/teachers/order_reserving.html.haml
- provide(:title, t('.title'))

= render "layouts/header"
%div.p_main
  %div.p_wrapper
    = render :partial => "profile"
    %div.p_content
      %div.p_block
        %div.p_block_title.p_content_block_title
          %h4
            = image_tag("yyz.png",class:"icont")
            预约中的订单
      %div.p_block
        = render "order_list"

app/views/teachers/paper.html.haml
- provide(:title, t('.title'))

= render "layouts/header"
%div.p_main
  %div.p_wrapper
    = render :partial => "profile"
    %div.p_content
      %div.p_block
        %div.p_block_title.p_content_block_title
          %h4
            = image_tag("zgrz.png",class:"icont")
            资格认证
            %span.p_titlexg 认证通过才能发布课程呦！
      %div.p_block
        .t_right
        = form_for current_teacher,:url=>upload_teachers_path,:html => {:multipart => true,:method=>'post'} do |f|
          = hidden_field_tag "item_img",Setting.teachers.item_img_paper
          .t_basic_info
            .cosl-md-12
            %h5身份认证
            .t_pass
              .sf
                个人身份认证
              .zs
                家教网老师必须为通过通过身份认证的真实老师！
                <input type="button" onclick="pass(0)" value="认证" class="btn btn-primary">
            .t_pass_00
              .t_pass_inf
                = image_tag("example.png",class:"img-thumbnail",width:"100px",height:"100px") 
                .t_prompt
                  参考示例
                  %br
                  1 照片放大后，身份证上的文字信息与身份证号清楚可见
                  %br
                  2 大小不要超过5M
                .clf
              .t_pass_inf
                -if current_teacher.paper_id_img.blank?
                  = image_tag("photo.jpg",class:"img-thumbnail",width:"100px",height:"100px")  
                -else
                  = image_tag(current_teacher.paper_id_img_url(:normal),class:"img-thumbnail",width:"100px",height:"100px")  
                .t_prompt  
                  = f.file_field :paper_id_img
                .clf
            %h5资质认证
            .t_pass
              .sf
                学历认证
              .zs
                学历认证可以提高个人认证的可信度！(在校生可用学生证代替)
                <input type="button" onclick="pass(1)" value="认证" class="btn btn-primary">
            .t_pass_01
              .t_pass_inf
                -if current_teacher.paper_img.blank?
                  = image_tag("photo.jpg",class:"img-thumbnail",width:"100px",height:"100px")  
                -else
                  = image_tag(current_teacher.paper_img_url(:normal),class:"img-thumbnail",width:"100px",height:"100px")  
                .t_prompt  
                  = f.file_field :paper_img
                .clf
            .t_pass
              .sf
                教师证认证
              .zs
                可以提升学生对家教专业技能的信任度！(在校学生可不用上传)
                <input type="button" onclick="pass(2)" value="认证" class="btn btn-primary">
            .t_pass_02
              .t_pass_inf
                -if current_teacher.teacher_paper.blank?
                  = image_tag("photo.jpg",class:"img-thumbnail",width:"100px",height:"100px")  
                -else
                  = image_tag(current_teacher.teacher_paper_url(:normal),class:"img-thumbnail",width:"100px",height:"100px")  
                .t_prompt  
                  = f.file_field :teacher_paper
                .clf
            .t_pass
              .sf
                专业资质认证
              .zs
                可以提升学生对家教专业技能的信任度！
                <input type="button" onclick="pass(3)" value="认证" class="btn btn-primary">
            .t_pass_03
              .t_pass_inf
                -if current_teacher.professional_paper.blank?
                  = image_tag("photo.jpg",class:"img-thumbnail",width:"100px",height:"100px")  
                -else
                  = image_tag(current_teacher.professional_paper_url(:normal),class:"img-thumbnail",width:"100px",height:"100px")  
                .t_prompt  
                  = f.file_field :professional_paper
                .clf
          =f.submit "提交",:class=>"btn btn-success t_btn"