config/routes.rb
Crystal::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :teachers, controllers:{registrations: "teachers/registrations"}
  ActiveAdmin.routes(self)

  resources :teachers, :only=>[]  do 
    get :basicInfor, :on => :collection
    get :editInfor, :on => :collection
    get :editinfo_experience, :on => :collection
    get :editinfo_plan, :on => :collection
    get :editinfo_study, :on => :collection
    get :editinfo_basic, :on => :collection
    post :updateInfor, :on => :collection
    get :paper, :on => :collection
    post :upload, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_transfer, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :detail,:on => :collection
    get :gallery,:on=>:collection
    get :show_menu,:on=>:collection
    get :sign_today,:on=>:collection
  end

  devise_for :parents, controllers: { registrations: "parents/registrations", sessions: "parents/sessions" }
  ActiveAdmin.routes(self)

  devise_scope :parent do
    get '/parent_validate', to: 'parents/sessions#parent_validate'
  end

  resources :parents, :only => [] do 
    get :activity, :on => :collection
    get :profile, :on => :collection
    get :modify_info, :on => :collection
    put :modify_info_changed, :on => :collection
    get :modify_password, :on => :collection
    put :modify_password_changed, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_refund, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :show_menu,:on=>:collection
  end

  resources :courses do
    get :select_second, :on=>:collection
    get :select_third, :on=>:collection
  end

  resources :addresses
  
  resources :comments, :only => [:index, :new, :create]
  
  resources :orders, :only => [:new, :create] do
    get :parent, :on => :collection
    get :teacher, :on => :collection
    get :parent_pay, :on => :collection
    get :teacher_pay, :on => :collection
  end

  resources :trades, :only => [:show] do
    post :alipay_notify, :on => :collection
  end

  resources :messages, :only => [:show]

  resources :notices, :only => [:index, :show] do
    get :list, :on=>:collection
    get :download, :on => :collection
  end

  resources :information, :only=>[:index, :show, :new, :create] do
    get :download, :on => :collection
  end

  resources :institutions, :only=>[:index]

  match '/activities/bonus' => 'activities#bonus'
  match '/activities/beauty' => 'activities#beauty'
  match '/activities/beauty2' => 'activities#beauty2'
  #post '/activities/vote_create2' => 'activities#vote_create2'
  #post '/activities/vote_code_validate' => 'activities#vote_code_validate'

  match '/filters/index' => 'filters#index'
  match '/filters/search' => 'filters#search'
  match '/subject/:number' => 'filters#subject'
  match '/filters/select/:school/:grade/:course/:sex/:period/:time',:controller => 'filters',:action => 'select'
  match '/login' => 'home#login'
  match '/sign_up' => 'home#sign_up'
  match '/flow' => 'home#flow'
  match '/tflow' => 'home#tflow'

  root :to => 'home#index'
end

app/controllers/courses_controller.rb
# encoding: UTF-8

class CoursesController < ApplicationController
  #这条语句不生效
  #before_filter {:authenticate_teacher! or :authenticate_parent!}
  load_and_authorize_resource
  has_mobile_fu
  has_mobile_fu_for :new,:index,:show,:edit
  def index
    @courses=current_teacher.courses.all
  end
  
  def show
    @course = Course.find(params[:id])
  end

  def new
    if current_teacher and current_teacher.status==Setting.teachers.status_pass_sql
      @course = Course.new
      @category = Category.all
      @category_json=@category.to_json
      @seconds = seconds
    else
      flash[:error] = t('courses.new.error')
     # redirect_to paper_teachers_path
       redirect_to editinfo_basic_teachers_path
    end
  end

  def edit
    if current_teacher and current_teacher.status==Setting.teachers.status_pass_sql
      @course = Course.find(params[:id])
      @category = Category.all
      @category_json=@category.to_json
      @seconds = seconds
      @thirds = thirds(@course.category.second)
      @subjects = subjects(@course.category.second,@course.category.third)
    else
      flash[:error] = t('courses.edit.error')
      redirect_to paper_teachers_path
    end
  end

  def create
    @course = Course.new(params[:course])
    @course.mode = "一对一教学"
    @course.teacher = current_teacher
    @category = Category.where(:subject=>params[:subject][:no3],:second=>params[:second][:no1],:third=>params[:third][:no2]).first
    @course.category = @category
    if @course.category.second == "计算机" or @course.category.second == "艺术"
      @course.name = @category.third + "-" + @category.subject
    else
      @course.name = @category.second + @category.third + @category.subject
    end
    if @course.save
      @category2 = Category.all
      @category_json=@category2.to_json
      @seconds = seconds
      flash.now[:success] = t('courses.create.success')
      redirect_to @course
    else
      #flash.now[:error] = t('courses.create.error')
      render action: "new"
    end
  end

  def update
    @course = Course.find(params[:id])
    @category = Category.where(:subject=>params[:subject][:no3],:second=>params[:second][:no1],:third=>params[:third][:no2]).first
    @course.category = @category
    @course.name = @category.second + @category.third + @category.subject
    if @course.update_attributes(params[:course])
      flash.now[:success] = t('courses.update.success')
      redirect_to @course
    else
      #flash.now[:error] = t('courses.update.error')
      render action: "edit"
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    flash.now[:success] = t('courses.destroy.success')
    redirect_to courses_url
  end

  def select_second
     @seconds=Category.where(:second=>params[:sec]).select("third").group("third").all.collect{|item| [item.third]}
     respond_to do |format|
       format.html
      format.json{ render :json => @seconds} 
     end
  end

  def select_third
    @thirds=Category.where(:second=>params[:sec],:third=>params[:third]).select("subject").all.collect{|ttem| [ttem.subject]}
    respond_to do |format|
      format.html
      format.json{ render :json => @thirds}
    end
  end

private
  def seconds
    cat=Category.select("second").order("id asc").group("second")
    res = []
    r =  ['请选择分类',0]
    res << r
    cat.each do|c|
      option = ["#{c.second}","#{c.second}"]
      res << option
    end
    return res
  end

  def thirds(second)
    c1=Category.where(:second=>second).select("third").group("third").all
    res = []
    r =  ['请选择二级分类',0]
    res << r
    c1.each do|i|
      r = ["#{i.third}","#{i.third}"]
      res << r
    end
    return res
  end

  def subjects(second,third)
    c2=Category.where(:second=>second,:third=>third).select("subject").all
    res = []
    r =  ['请选择科目',0]
    res << r
    c2.each do|j|
      r = ["#{j.subject}","#{j.subject}"]
      res << r
    end
    return res
  end
end

app/helpers/courses_helper.rb
#encoding:utf-8
module CoursesHelper
  def mode_option
    [['一对一教学','一对一教学']]
  end

  def price_options
    [['20','20'],['30','30'],['40','40'],['50','50'],['60','60'],['70','70'],['80','80'],['90','90'],['100','100'],['120','120'],['150','150'],['200','200']]
  end

  def format_string_newline(text)
    if text
      text.gsub("\r\n", "<br/>")
    else
      ""
    end
  end
end

app/views/courses/_form.html.haml
= form_for @course, :html=>{:class=>"form-horizontal course_form"}, :validate => true do |f|
  = form_error_messages!(@course)
  -#
    .form-group
      = f.label "课程名称", :class=>"col-md-2 col-xs-2 control-label"
      .col-md-4.col-xs-4
        = f.text_field :name,:class=>"form-control"
      %span.promot-part= "（* 必填）"

  - if request.path == new_course_path
    .form-group
      = f.label "科目分类", :class=>"col-md-2 col-xs-2 control-label"
      .col-md-4.col-xs-4
        .form-group
          = select "second","no1",@seconds,{:include_balnk=>true},{:class=>"form-control ctg_list",:onchange=>"select_no1_category(this,#{@category_json})"} 
        .form-group
          = select "third","no2",{},{:include_blank=>true},{:class=>"form-control ctg_list",:onchange=>"select_no2_category(this,#{@category_json})"}
        .form-group 
          = select "subject","no3",{},{:include_blank=>true},{:class=>"form-control ctg_list",:onblur=>"check_select(this)"}
      %span.promot-parts= "（* 必填）"
  - else
    .form-group
      = f.label "科目分类", :class=>"col-md-2 col-xs-2 control-label"
      .col-md-4.col-xs-4
        = select "second","no1",options_for_select(@seconds,selected:@course.category.second),{:include_balnk=>true},{:class=>"form-control ctg_list",:onchange=>"select_no1_category(this,#{@category_json})"} 
        = select "third","no2",options_for_select(@thirds,selected:@course.category.third),{:include_balnk=>true},{:class=>"form-control ctg_list",:onchange=>"select_no2_category(this,#{@category_json})"} 
        = select "subject","no3",options_for_select(@subjects,selected:@course.category.subject),{:include_balnk=>true},{:class=>"form-control ctg_list"} 
      %span.promot-parts= "（* 必填）"

  -#
    .form-group
      = f.label "授课模式", :class=>"col-md-2 col-xs-2 control-label"
      .col-md-4.col-xs-4
        = f.select :mode,mode_option,{:include_blank=>false},{:class=>"form-control"}
      %span.promot-part= "（* 必填）"

    .form-group
      = f.label "授课时长", :class=>"col-md-2 col-xs-2 control-label"
      .col-md-4.col-xs-4
        = f.number_field :length, :class=>"form-control"
      .col-md-2.col-xs-2
        = f.label "小时",:class=>"form-control-static"
        %span.promot-part= "（* 必填）"
      
  .form-group
    = f.label "课时费用", :class=>"col-md-2 col-xs-2 control-label"
    .col-md-4.col-xs-4
      = f.select :price,options_for_select(price_options,@course.price),{:include_blank=>false},{:class => "form-control"}
    .col-md-2.col-xs-2
      = f.label "元/时", :class=>"form-control-static"
      %span.promot-part= "（* 必填）"
    %p.pinfo (课时费用既是试讲费用，也是正式上课费用，两者相同，家长将会按照这个费用支付订单！)
  
  .form-group
    .col-md-3.col-xs-3.col-md-offset-2.col-xs-offset-2
      %input{:type=>"button",:value=>"发布",:onclick=>"submit_course()",:class=>"btn btn-success"}
      &nbsp;&nbsp;
      = link_to '返回',courses_path,:class=>"btn btn-default"

app/views/courses/_form.mobile.haml
= form_for @course, :html=>{:class=>"form-horizontal course_form"}, :validate => true do |f|
  = form_error_messages!(@course)
  %h5 科目分类
  - if request.path == new_course_path
    .row
      .col-xs-10.col-xs-offset-1
        .form-group
          = select "second","no1",@seconds,{:include_balnk=>true},{:class=>"form-control",:onchange=>"select_no1_category(this,#{@category_json})"} 
      .col-xs-10.col-xs-offset-1
        .form-group
          = select "third","no2",{},{:include_blank=>true},{:class=>"form-control",:onchange=>"select_no2_category(this,#{@category_json})"}
      .col-xs-10.col-xs-offset-1
        .form-group 
          = select "subject","no3",{},{:include_blank=>true},{:class=>"form-control",:onblur=>"check_select(this)"}
  - else
    .row
      .form-group
        .col-xs-8.col-xs-offset-2
          .form-group
            = select "second","no1",options_for_select(@seconds,selected:@course.category.second),{:include_balnk=>true},{:class=>"form-control",:onchange=>"select_no1_category(this,#{@category_json})"} 
        .col-xs-8.col-xs-offset-2
          .form-group
            = select "third","no2",options_for_select(@thirds,selected:@course.category.third),{:include_balnk=>true},{:class=>"form-control",:onchange=>"select_no2_category(this,#{@category_json})"} 
        .col-xs-8.col-xs-offset-2
          .form-group
            = select "subject","no3",options_for_select(@subjects,selected:@course.category.subject),{:include_balnk=>true},{:class=>"form-control"} 
  .row
    .col-xs-4
      %h5 课时费用
    .col-xs-4
      = f.select :price,options_for_select(price_options,@course.price),{:include_blank=>false},{:class => "form-control"}
    .col-xs-4
      %h5 元/时
  %h4
    %small 课时费用既是试讲费用，也是正式上课费用，两者相同，家长将会按照这个费用支付订单！
  %hr
  = f.submit '发布课程', :class=>"btn btn-success btn-block"
  

app/views/courses/edit.html.haml
- provide(:title, t('.title'))

%div#p_header
  %div.p_wrapper
    %div.p_logo
      同城家教
    %img.p_title_img{:src => "https://account.xiaomi.com/static/img/passport/photo.jpg"}
    %div.p_title
      个人主页
%div.p_main
  %div.p_wrapper
    = render :partial => "teachers/profile"
    %div.p_content
      %div.p_block
        %div.p_block_title.p_content_block_title
          %h4
            %i.glyphicon.glyphicon-user
            编辑课程
      %div.p_block
        %div.t_main
          %div.t_right
            %div.show
              %div.panel-body
                = render :partial => "form"

app/views/courses/edit.mobile.haml
- provide(:title, t('.title'))
=render "layouts/header"
= render :partial => "form"

app/views/courses/index.html.haml
- provide(:title, t('.title'))

%div#p_header
  %div.p_wrapper
    %div.p_logo
      %a{:href => root_path}
        =image_tag('logo.png',:class => "header-logo-img2")
    %img.p_title_img{:src => "https://account.xiaomi.com/static/img/passport/photo.jpg"}
    %div.p_title
      个人主页
%div.p_main
  %div.p_wrapper
    = render :partial => "teachers/profile"
    %div.p_content
      %div.p_block
        %div.p_block_title.p_content_block_title
          %h4
            = image_tag("qbkc.png",class:"icont")
            已发布课程
        %div.p_block
          %br       
          - @courses.each_slice(3) do |slice|
            .row
              .col-md-12
                - slice.each do |course|
                  .container1
                    .qa-message-list#wallmessages
                      .message-item#md16
                        .message-inner
                          .clearfix
                            %table.col-md-12#c_table
                              %tr.c_header
                                %td{:colspan=>4}
                                  %span="发布时间"
                                  %span="| #{course.updated_at.strftime("%Y-%m-%d %H:%M:%S")}"
                              %tr.c_content
                    
                                %td.black-link.col-md-3
                                  = link_to course.name,course_path(course)
                                %td.col-md-3
                                  = "授课时长: #{course.length} 小时"
                                %td.col-md-3
                                  = "试讲费用: #{course.price} 元"
                                %td.col-md-3
                                  = link_to '删除',course,:method=>:delete,:data=>{:confirm=>"确认删除课程吗？"},:class=>"btn btn-danger"
                                  = link_to '修改',edit_course_path(course),:class => "btn btn-info"
          

app/views/courses/index.mobile.haml
- provide(:title, t('.title'))

=render "layouts/header"
- @courses.each_slice(3) do |slice|
  - slice.each do |course|
    .qa-message-list#wallmessages
      .message-item#m16
        .message-inner
          .message-head.clearfix
            %h5 
              = link_to course.name,course_path(course)
          .qa-message-content
            %p
              发布时间:
              =course.updated_at.strftime("%Y-%m-%d %H:%M:%S")
            %p
              授课时长: 
              ="#{course.length} 小时"
            %p
              试讲费用:
            = link_to '删除',course,:method=>:delete,:data=>{:confirm=>"确认删除课程吗？"},:class=>"btn btn-danger"
            = link_to '修改',edit_course_path(course),:class => "btn btn-info"

app/views/courses/new.html.haml
- provide(:title, t('.title'))

%div#p_header
  %div.p_wrapper
    %div.p_logo
      %a{:href => root_path}
        =image_tag('logo.png',:class => "header-logo-img2")
    %img.p_title_img{:src => "https://account.xiaomi.com/static/img/passport/photo.jpg"}
    %div.p_title
      个人主页
%div.p_main
  %div.p_wrapper
    = render :partial => "teachers/profile"
    %div.p_content
      %div.p_block
        %div.p_block_title.p_content_block_title
          %h4
            %i.glyphicon-color.glyphicon.glyphicon-circle-arrow-up
            发布课程
      %div.p_block
        %div.t_main
          %div.t_right
            %div.show
              %div.panel-body
                = render :partial => "form"

app/views/courses/new.mobile.haml
- provide(:title, t('.title'))

= render "layouts/header"
= render :partial => "form"

app/views/courses/show.html.haml
- provide(:title, t('.title'))

%div#p_header
  %div.p_wrapper
    %div.p_logo
      %a{:href => root_path}
        =image_tag('logo.png',:class => "header-logo-img2")
    %img.p_title_img{:src => "https://account.xiaomi.com/static/img/passport/photo.jpg"}
    %div.p_title
      个人主页
%div.p_main
  %div.p_wrapper
    = render :partial => "teachers/profile"
    %div.p_content
      %div.p_block
        %div.p_block_title.p_content_block_title
          %h4
            %i.glyphicon.glyphicon-user
              课程信息
      %div.p_block
        %div.t_main
          %div.t_right
            %div.show
              %div.panel-body
                = form_for @course, :html=>{:class=>"form-horizontal"} do |f|
                  .form-group
                    = f.label "课程名称", :class=>"col-md-2 col-xs-2 control-label"
                    .col-md-4.col-xs-4
                      %p.form-control= @course.name

                  .form-group
                    = f.label "科目分类", :class=>"col-md-2 col-xs-2 control-label"
                    .col-md-4.col-xs-4
                      %p.form-control="#{@course.category.second} / #{@course.category.third} / #{@course.category.subject}"

                  -#
                    .form-group
                      = f.label "授课时期", :class=>"col-md-2 control-label"
                      .col-md-4.col-xs-4
                        %label.radio-inline
                          = f.radio_button :period, Setting.courses.period_normal, :disabled=>true
                          = Setting.courses.period_normal_string
                        %label.radio-inline
                          = f.radio_button :period, Setting.courses.period_vacation, :disabled=>true
                          = Setting.courses.period_vacation_string
                        %label.radio-inline
                          = f.radio_button :period, Setting.courses.period_all, :disabled=>true
                          = Setting.courses.period_all_string

                    .form-group
                      = f.label "授课经验", :class=>"col-md-2 control-label"
                      .col-md-4.col-xs-4
                        %p.form-control= @course.experence
                      = f.label "年", :class=>"form-control-static"
                
                    .form-group
                      = f.label "授课模式", :class=>"col-md-2 control-label"
                      .col-md-4.col-xs-4
                        %p.form-control= @course.mode
                
                    .form-group
                      = f.label "授课时长", :class=>"col-md-2 control-label"
                      .col-md-4.col-xs-4
                        %p.form-control= @course.length
                      = f.label "小时", :class=>"form-control-static"
                
                  .form-group
                    = f.label "课时费用", :class=>"col-md-2 col-xs-2 control-label"
                    .col-md-4.col-xs-4
                      %p.form-control= @course.price
                    = f.label "元 / 时", :class=>"form-control-static"
                
                  -#
                    .form-group
                      = f.label "预约时间", :class=>"col-md-2 control-label"
                      .col-md-7
                        %table.table.table-bordered
                          %tr
                            %td
                              ="星期一"
                              = check_box_tag "appointments_pos[]",1,@appointments_pos.include?(1)
                            %td
                              ="星期二"
                              = check_box_tag "appointments_pos[]",2,@appointments_pos.include?(2)
                            %td
                              ="星期三"
                              = check_box_tag "appointments_pos[]",3,@appointments_pos.include?(3)
                            %td
                              ="星期四"
                              = check_box_tag "appointments_pos[]",4,@appointments_pos.include?(4)
                            %td
                              ="星期五"
                              = check_box_tag "appointments_pos[]",5,@appointments_pos.include?(5)
                            %td
                              ="星期六"
                              = check_box_tag "appointments_pos[]",6,@appointments_pos.include?(6)
                            %td
                              ="星期日"
                              = check_box_tag "appointments_pos[]",7,@appointments_pos.include?(7)
                  
                  .form-group
                    .col-md-6.col-xs-6.col-md-offset-2.col-xs-offset-2
                      = link_to '编辑', edit_course_path(@course), :class=>"btn btn-primary"
                      &nbsp;
                      = link_to '删除', @course, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-danger"
                      &nbsp;
                      = link_to '返回',courses_path,:class=>"btn btn-default"

app/views/courses/show.mobile.haml
- provide(:title, t('.title'))
= render "layouts/header"
.m-top-00
= form_for @course, :html=>{:class=>"form-horizontal"} do |f|
  .form-group
    .col-xs-6
      = f.label "课程名称", :class=>"col-xs-12 control-label"
    .col-xs-6
      = @course.name
  .form-group
    .col-xs-6
      = f.label "科目分类", :class=>"col-xs-12 control-label"
    .col-xs-6
      ="#{@course.category.second} / #{@course.category.third} / #{@course.category.subject}"
  .form-group
    .col-xs-6
      = f.label "课时费用", :class=>"col-xs-12 control-label"
    .col-xs-6
      ="#{ @course.price} 元/时"
  %hr
  .form-group
    .col-xs-6
      = link_to '编辑', edit_course_path(@course), :class=>"col-xs-12 btn btn-primary"
    .col-xs-6
      = link_to '删除', @course, :method => :delete, :data => { :confirm =>"#{t('courses.delete.title')}" }, :class=>"btn btn-danger col-xs-12"