config/routes.rb
Crystal::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :teachers, controllers:{registrations: "teachers/registrations"}
  ActiveAdmin.routes(self)

  resources :teachers, :only=>[]  do 
    get :basicInfor, :on => :collection
    get :editInfor, :on => :collection
    get :editinfo_experience, :on => :collection
    get :editinfo_plan, :on => :collection
    get :editinfo_study, :on => :collection
    get :editinfo_basic, :on => :collection
    post :updateInfor, :on => :collection
    get :paper, :on => :collection
    post :upload, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_transfer, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :detail,:on => :collection
    get :gallery,:on=>:collection
    get :show_menu,:on=>:collection
    get :sign_today,:on=>:collection
  end

  devise_for :parents, controllers: { registrations: "parents/registrations", sessions: "parents/sessions" }
  ActiveAdmin.routes(self)

  devise_scope :parent do
    get '/parent_validate', to: 'parents/sessions#parent_validate'
  end

  resources :parents, :only => [] do 
    get :activity, :on => :collection
    get :profile, :on => :collection
    get :modify_info, :on => :collection
    put :modify_info_changed, :on => :collection
    get :modify_password, :on => :collection
    put :modify_password_changed, :on => :collection
    get :order_all, :on => :collection
    get :order_unpay, :on => :collection
    get :order_reserving, :on => :collection
    get :order_refund, :on => :collection
    get :messages, :on => :collection
    get :msg, :on => :collection
    get :show_menu,:on=>:collection
  end

  resources :courses do
    get :select_second, :on=>:collection
    get :select_third, :on=>:collection
  end

  resources :addresses
  
  resources :comments, :only => [:index, :new, :create]
  
  resources :orders, :only => [:new, :create] do
    get :parent, :on => :collection
    get :teacher, :on => :collection
    get :parent_pay, :on => :collection
    get :teacher_pay, :on => :collection
  end

  resources :trades, :only => [:show] do
    post :alipay_notify, :on => :collection
  end

  resources :messages, :only => [:show]

  resources :notices, :only => [:index, :show] do
    get :list, :on=>:collection
    get :download, :on => :collection
  end

  resources :information, :only=>[:index, :show, :new, :create] do
    get :download, :on => :collection
  end

  resources :institutions, :only=>[:index]

  match '/activities/bonus' => 'activities#bonus'
  match '/activities/beauty' => 'activities#beauty'
  match '/activities/beauty2' => 'activities#beauty2'
  #post '/activities/vote_create2' => 'activities#vote_create2'
  #post '/activities/vote_code_validate' => 'activities#vote_code_validate'

  match '/filters/index' => 'filters#index'
  match '/filters/search' => 'filters#search'
  match '/subject/:number' => 'filters#subject'
  match '/filters/select/:school/:grade/:course/:sex/:period/:time',:controller => 'filters',:action => 'select'
  match '/login' => 'home#login'
  match '/sign_up' => 'home#sign_up'
  match '/flow' => 'home#flow'
  match '/tflow' => 'home#tflow'

  root :to => 'home#index'
end

app/controllers/filters_controller.rb
# encoding: UTF-8
class FiltersController < ApplicationController
  has_mobile_fu
  has_mobile_fu_for :index, :select, :subject, :search

  def select
    if params[:school] != "all"
      @subjects = Category.select("subject").where("second = '#{params[:school]}'").group("subject").order("id")
    end

    condition_category = ""
    if params[:school] != "all" && params[:school] != nil
       condition_category += " second = '#{params[:school]}'"
    end
    if params[:course] != "all" && params[:course] != nil
      if condition_category != ""
        condition_category += " and subject = '#{params[:course]}'"
      else
        condition_category += " subject = '#{params[:course]}'"
      end
    end
    @courses = Course.where(:category_id => Category.where(condition_category)).group("teacher_id")

    @teachers = []
    @courses.map do |course|
      if course.teacher
        if params[:period] == "all" || course.period.to_s == params[:period] || course.period == Setting.courses.period_all
          if params[:sex] == "all" || course.teacher.sex.to_s == params[:sex]
            weekdays = course.teacher.appointments.map {|a| a.weekday.to_s}
            if params[:time] == "all" || weekdays.include?(params[:time])
              @teachers << course.teacher
            end
          end
        end
      end
    end
    @teachers.uniq!{|t| t.id}
    @teachers.sort!{|a,b| compute(b.score,b.signcount)<=>compute(a.score,a.signcount)}
    @teachers.reject!{|t| t.status != Setting.teachers.status_pass_sql}
  end

  def index
    @courses = Course.all
    @courses = @courses.select {|c| c.teacher != nil}
    @teachers = @courses.map {|course| course.teacher}
    @teachers.uniq!{|t| t.id}
    @teachers.sort!{|a,b| compute(b.score,b.signcount)<=>compute(a.score,a.signcount)}
    @teachers.reject!{|t| t.status != Setting.teachers.status_pass_sql}
  end

  def subject
    @category = Category.find_by_number(params[:number])
    params[:school] = @category.second
    params[:grade] = "all"
    params[:course] = @category.subject
    params[:sex] = "all"
    params[:period] = "all"
    params[:time] = "all"
    select
    render "subject"
  end

  def search
    params[:school] = "all"
    params[:grade] = "all"
    params[:course] = "all"
    params[:sex] = "all"
    params[:period] = "all" 
    params[:time] = "all"
    @courses = Course.where(:category_id => Category.where("subject like ?", "%#{params[:keywords]}%").select("id"))
    @teachers = []
    @courses.each do |course|
      @teachers << course.teacher if course.teacher
    end
    @teachers.uniq!{|t| t.id}
    @teachers.sort!{|a,b| compute(b.score,b.signcount)<=>compute(a.score,a.signcount)}
    @teachers.reject!{|t| t.status != Setting.teachers.status_pass_sql}
  end

  private

  def compute(score, signcount)
    new_signcount = signcount ? signcount : 0
    new_signcount = new_signcount>5 ? 5 : new_signcount
    score + new_signcount * 4
  end
end

app/helpers/filters_helper.rb
# encoding: UTF-8
module FiltersHelper
  def get_week_string(week)
  
    if week != nil   
      if week == Setting.appointments.weekday_monday.to_s()
        Setting.appointments.weekday_monday_string.to_s()
      elsif week == Setting.appointments.weekday_tuesday.to_s()
        Setting.appointments.weekday_tuesday_string.to_s()
      elsif week == Setting.appointments.weekday_thursday.to_s() 
        Setting.appointments.weekday_thursday_string.to_s()
      elsif week == Setting.appointments.weekday_friday.to_s()
        Setting.appointments.weekday_friday_string.to_s()
      elsif week == Setting.appointments.weekday_wednesday.to_s()
        Setting.appointments.weekday_wednesday_string.to_s()
      elsif week == Setting.appointments.weekday_saturday.to_s()
        Setting.appointments.weekday_saturday_string.to_s()
      elsif week == Setting.appointments.weekday_sunday.to_s()
        Setting.appointments.weekday_sunday_string.to_s()
      end
    end
  end

  def get_time_string(time)
  
    if time != nil   
      if time == Setting.appointments.time_morning.to_s() 
        Setting.appointments.time_morning_string.to_s()
      elsif time == Setting.appointments.time_afternoon.to_s()
        Setting.appointments.time_afternoon_string.to_s()
      elsif time == Setting.appointments.time_evening.to_s()
        Setting.appointments.time_evening_string.to_s()
      end
    end
  end

  def get_color_string(course)
    if course.to_s() == Setting.colors.courses_yw.to_s()
      Setting.colors.courses_yw_color.to_s()
    elsif  course.to_s() == Setting.colors.courses_sx.to_s()
      Setting.colors.courses_sx_color.to_s()
    elsif course.to_s() == Setting.colors.courses_yy.to_s()
      Setting.colors.courses_yy_color.to_s()
    elsif course.to_s() == Setting.colors.courses_wl.to_s()
      Setting.colors.courses_wl_color.to_s()
    elsif course.to_s() == Setting.colors.courses_hx.to_s()
      Setting.colors.courses_hx_color.to_s()
    elsif course.to_s() == Setting.colors.courses_sw.to_s()
      Setting.colors.courses_sw_color.to_s()
    elsif course.to_s() == Setting.colors.courses_zz.to_s()
      Setting.colors.courses_zz_color.to_s()
    elsif course.to_s() == Setting.colors.courses_ls.to_s()
      Setting.colors.courses_ls_color.to_s()
    elsif course.to_s() == Setting.colors.courses_dl.to_s()
      Setting.colors.courses_dl_color.to_s()
    else
      Setting.colors.courses_qt_color.to_s()
    end
  end

  def get_min_price(courses)
    price = courses[0].price
    courses.each do |c|
      price = c.price if c.price < price
    end
    return price
  end
end

app/views/filters/_filter.html.haml
%div#search-item-div
  .div.wrapper
    %div.search-item-title
      = "课程筛选 我们已经为您搜索出相关的老师。"
    %div.search-item-box
      %table.table
        %tr
          %td{:width => "100px"}
            学生课程:
          %td{:align => "left"}
            %ul
              %li{:class =>  (params[:school] == "all" ? "search-active" : nil)}
                = link_to "全部","/filters/select/all/all/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
              %li{:class => (params[:school] == "小学" ? "search-active" : nil)}
                = link_to "小学","/filters/select/小学/all/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
              %li{:class => (params[:school] == "初中" ? "search-active": nil)}
                = link_to "初中","/filters/select/初中/all/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
              %li{:class => (params[:school] == "高中" ? "search-active" : nil)}
                = link_to "高中","/filters/select/高中/all/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
              %li{:class => (params[:school] == "艺术" ? "search-active" : nil)}
                = link_to "艺术","/filters/select/艺术/#{params[:grade]}/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
              %li{:class => (params[:school] == "计算机" ? "search-active" : nil)}
                = link_to "计算机","/filters/select/计算机/#{params[:grade]}/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
            -#
              %ul.grade-div
                - if params[:school] != "all" && params[:school] != nil 
                  %li{:class =>  (params[:grade] == "all" ? "search-active" : nil)}
                    = link_to "全部","/filters/select/#{params[:school]}/all/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/"
                  %li{:class => (params[:grade] == "一年级" ? "search-active" : nil)}
                    = link_to "一年级","/filters/select/#{params[:school]}/一年级/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/"
                  %li{:class => (params[:grade] == "二年级" ? "search-active": nil)}
                    = link_to "二年级","/filters/select/#{params[:school]}/二年级/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/"
                  %li{:class => (params[:grade] == "三年级" ? "search-active" : nil)}
                    = link_to "三年级","/filters/select/#{params[:school]}/三年级/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/"
                - if params[:school] != "all" && params[:school] !=nil && params[:school] == '小学'
                  %li{:class => (params[:grade] == "四年级" ? "search-active" : nil)}
                    = link_to "四年级","/filters/select/#{params[:school]}/四年级/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/"
                  %li{:class => (params[:grade] == "五年级" ? "search-active": nil)}
                    = link_to "五年级","/filters/select/#{params[:school]}/五年级/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/"
                  %li{:class => (params[:grade] == "六年级" ? "search-active" : nil)}
                    = link_to "六年级","/filters/select/#{params[:school]}/六年级/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/"
            - if params[:school] and params[:school] != "all" 
              %ul.grade-div
                %li{:class => (params[:course] == "all" ? "search-active" : nil)}
                  = link_to "全部","/filters/select/#{params[:school]}/all/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
                - @subjects.each do |f|
                  %li{:class => (params[:course].to_s() == f.subject.to_s() ? "search-active" : nil)}
                    = link_to f.subject,"/filters/select/#{params[:school]}/#{params[:grade]}/#{f.subject}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
        %tr
          %td
            家教性别:
          %td
            %ul 
              %li{:class => (params[:sex] == "all" ? "search-active" : nil)}
                = link_to "全部","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/all/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
              %li{:class => (params[:sex] == "1" ? "search-active" : nil)}
                = link_to "男","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/1/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
              %li{:class => (params[:sex] == "2" ? "search-active" : nil)}
                = link_to "女","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/2/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
        %tr
          %td
            授课时期:
          %td
            %ul
              %li{:class => (params[:period] == "all" ? "search-active" : nil)}
                = link_to "全部","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/all/#{params[:time]}", :rel=>"nofollow"
              %li{:class => (params[:period] == "0" ? "search-active" : nil)}
                = link_to "平时可以","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/0/#{params[:time]}", :rel=>"nofollow"
              %li{:class => (params[:period] == "1" ? "search-active" : nil)}
                = link_to "假期可以","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/1/#{params[:time]}", :rel=>"nofollow"

        -#
          %tr
            %td
              约课范围:
            %td
              %ul
                %li{:class => (params[:place] == "all" ? "search-active" : nil)}
                  = link_to "全部","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/all/#{params[:time]}/"
                %li{:class => (params[:place] == "1" ? "search-active" : nil)}
                  = link_to "船营区","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/1/#{params[:time]}/"
                %li{:class => (params[:place] == "2" ? "search-active" : nil)}
                  = link_to "昌邑区","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/2/#{params[:time]}/"
                %li{:class => (params[:place] == "3" ? "search-active" : nil)}
                  = link_to "丰满区","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/3/#{params[:time]}/"
                %li{:class => (params[:place] == "4" ? "search-active" : nil)}
                  = link_to "龙潭区","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/4/#{params[:time]}/"
                %li{:class => (params[:place] == "5" ? "search-active" : nil)}
                  = link_to "蛟河市","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/5/#{params[:time]}/"
                %li{:class => (params[:place] == "6" ? "search-active" : nil)}
                  = link_to "桦甸市","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/6/#{params[:time]}/"
                %li{:class => (params[:place] == "7" ? "search-active" : nil)}
                  = link_to "舒兰市","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/7/#{params[:time]}/"
                %li{:class => (params[:place] == "8" ? "search-active" : nil)}
                  = link_to "永吉区","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/8/#{params[:time]}/"
                %li{:class => (params[:place] == "9" ? "search-active" : nil)}
                  = link_to "磐石市","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/9/#{params[:time]}/"
        %tr
          %td
            约课时间:
          %td
            %ul
              %li{:class => (params[:time] == "all" ? "search-active" : nil )}
                = link_to "全部", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/all/", :rel=>"nofollow"
              %li{:class => (params[:time] == "1" ? "search-active" : nil )}
                = link_to "周一", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/1/", :rel=>"nofollow"
              %li{:class => (params[:time] == "2" ? "search-active" : nil )}
                = link_to "周二", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/2/", :rel=>"nofollow"
              %li{:class => (params[:time] == "3" ? "search-active" : nil )}
                = link_to "周三", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/3/", :rel=>"nofollow"
              %li{:class => (params[:time] == "4" ? "search-active" : nil )}
                = link_to "周四", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/4/", :rel=>"nofollow"
              %li{:class => (params[:time] == "5" ? "search-active" : nil )}
                = link_to "周五", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/5/", :rel=>"nofollow"
              %li{:class => (params[:time] == "6" ? "search-active" : nil )}
                = link_to "周六", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/6/", :rel=>"nofollow"
              %li{:class => (params[:time] == "0" ? "search-active" : nil )}
                = link_to "周日", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/0/", :rel=>"nofollow"

app/views/filters/_filter.mobile.haml
.row.header-search.form-group
  .col-xs-12
    %ul.list-inline
      %li
        学生课程:
      %li{:class =>  (params[:school] == "all" ? "search-active" : nil)}
        = link_to "全部","/filters/select/all/all/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
      %li{:class => (params[:school] == "小学" ? "search-active" : nil)}
        = link_to "小学","/filters/select/小学/all/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
      %li{:class => (params[:school] == "初中" ? "search-active": nil)}
        = link_to "初中","/filters/select/初中/all/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
      %li{:class => (params[:school] == "高中" ? "search-active" : nil)}
        = link_to "高中","/filters/select/高中/all/#{params[:course]}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
      %li{:class => (params[:school] == "艺术" ? "search-active" : nil)}
        = link_to "艺术","/filters/select/艺术/#{params[:grade]}/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
  .col-xs-12.appoint-left
    %ul.list-inline
      %li{:class => (params[:school] == "计算机" ? "search-active" : nil)}
        = link_to "电脑","/filters/select/计算机/#{params[:grade]}/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
  - if params[:school] and params[:school] != "all" 
    .col-xs-12
      .col-xs-12.bd-grey
        %p
          %ul.list-inline
            %li{:class => (params[:course] == "all" ? "search-active" : nil)}
              = link_to "全部","/filters/select/#{params[:school]}/all/all/#{params[:sex]}/#{params[:period]}/#{params[:time]}/",:class => "text-muted", :rel=>"nofollow"
            - @subjects.each do |f|
              %li{:class => (params[:course].to_s() == f.subject.to_s() ? "search-active" : nil)}
                = link_to f.subject,"/filters/select/#{params[:school]}/#{params[:grade]}/#{f.subject}/#{params[:sex]}/#{params[:period]}/#{params[:time]}/",:class => "text-muted", :rel=>"nofollow"
            
  .col-xs-12
    %ul.list-inline
      %li
        家教性别:
      %li{:class => (params[:sex] == "all" ? "search-active" : nil)}
        = link_to "全部","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/all/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
      %li{:class => (params[:sex] == "1" ? "search-active" : nil)}
        = link_to "男","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/1/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
      %li{:class => (params[:sex] == "2" ? "search-active" : nil)}
        = link_to "女","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/2/#{params[:period]}/#{params[:time]}/", :rel=>"nofollow"
  .col-xs-12
    %ul.list-inline
      %li
        授课时期:
      %li{:class => (params[:period] == "all" ? "search-active" : nil)}
        = link_to "全部","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/all/#{params[:time]}", :rel=>"nofollow"
      %li{:class => (params[:period] == "0" ? "search-active" : nil)}
        = link_to "平时可以","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/0/#{params[:time]}", :rel=>"nofollow"
      %li{:class => (params[:period] == "1" ? "search-active" : nil)}
        = link_to "假期可以","/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/1/#{params[:time]}", :rel=>"nofollow"
  .col-xs-12
    %ul.list-inline
      %li
        约课时间:
      %li{:class => (params[:time] == "all" ? "search-active" : nil )}
        = link_to "全部", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/all/", :rel=>"nofollow"
      %li{:class => (params[:time] == "1" ? "search-active" : nil )}
        = link_to "周一", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/1/", :rel=>"nofollow"
      %li{:class => (params[:time] == "2" ? "search-active" : nil )}
        = link_to "周二", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/2/", :rel=>"nofollow"
      %li{:class => (params[:time] == "3" ? "search-active" : nil )}
        = link_to "周三", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/3/", :rel=>"nofollow"
      %li{:class => (params[:time] == "4" ? "search-active" : nil )}
        = link_to "周四", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/4/", :rel=>"nofollow"
  .col-xs-12.appoint-left
    %ul.list-inline
      %li{:class => (params[:time] == "5" ? "search-active" : nil )}
        = link_to "周五", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/5/", :rel=>"nofollow"
      %li{:class => (params[:time] == "6" ? "search-active" : nil )}
        = link_to "周六", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/6/", :rel=>"nofollow"
      %li{:class => (params[:time] == "0" ? "search-active" : nil )}
        = link_to "周日", "/filters/select/#{params[:school]}/#{params[:grade]}/#{params[:course]}/#{params[:sex]}/#{params[:period]}/0/", :rel=>"nofollow"

app/views/filters/index.html.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top"

%div#menu
  %div.wrapper
    %div.menu-c-all
      = link_to "全部课程分类","/filters/index"
    %div.menu-m
      %ul
        %li
          = link_to "首页", root_path, :class => "menu-m-active"
        %li 
          = link_to "预约流程", flow_path, :class=>"menu-m-active"
        %li
          = link_to "家教入驻", tflow_path, :class=>"menu-m-active"
        %li
          = link_to "校园信息", information_index_path, :class=>"menu-m-active"
        .cui-ico-new

= render "filter_all"
= render "index"

app/views/filters/index.mobile.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top"

.row.filter-top
  .col-xs-12
    = render "filters/filter_all"
.row
  .col-xs-12.padding-nine
    = render "index"

app/views/filters/search.html.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top"

%div#menu
  %div.wrapper
    %div.menu-c-all
      = link_to "全部课程分类","/filters/index"
    %div.menu-m
      %ul
        %li
          = link_to "首页", root_path, :class => "menu-m-active"
        %li 
          = link_to "预约流程", flow_path, :class=>"menu-m-active"
        %li
          = link_to "家教入驻", tflow_path, :class=>"menu-m-active"
        %li
          = link_to "校园信息", information_index_path, :class=>"menu-m-active"
        .cui-ico-new

= render "filter"
= render "index"

app/views/filters/search.mobile.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top"

.row.filter-top
  .col-xs-12
    = render "filters/filter"
.row
  .col-xs-12.padding-nine
    = render "index"

app/views/filters/select.html.haml
- provide(:title, t('.title'))

= render "layouts/subbar_top"

%div#menu
  %div.wrapper
    %div.menu-c-all
      = link_to "全部课程分类","/filters/index"
    %div.menu-m
      %ul
        %li
          = link_to "首页", root_path, :class => "menu-m-active"
        %li 
          = link_to "预约流程", flow_path, :class=>"menu-m-active"
        %li
          = link_to "家教入驻", tflow_path, :class=>"menu-m-active"
        %li
          = link_to "校园信息", information_index_path, :class=>"menu-m-active"
        .cui-ico-new

= render "filter"
= render "index"

app/views/filters/select.mobile.haml
- provide(:title, t('.title')) 
= render "layouts/subbar_top"

.row.filter-top
  .col-xs-12
    = render "filters/filter"
.row
  .col-xs-12.padding-nine
    = render "index"